CREATE TABLE products ( 
product_id INT PRIMARY KEY, 
product_name VARCHAR(50), 
company VARCHAR(50), 
price DECIMAL(10, 2) 
); 
INSERT INTO products (product_id, product_name, company, price) 
VALUES 
(1, 'Smartphone', 'Flipkart', 1500.00), 
(2, 'Shoes', 'Myntra', 800.00), 
(3, 'Laptop', 'Flipkart', 50000.00), 
(4, 'T-shirt', 'Ajio', 500.00), 
(5, 'Headphones', 'Flipkart', 1200.00); 

-- Q12 Find all Flipkart products priced above 1000. 
SELECT * FROM products
where company= 'Flipkart'
and price >1000;

---------------------------------------------------------------------------
CREATE TABLE rides ( 
ride_id INT PRIMARY KEY, 
customer_name VARCHAR(50), 
company VARCHAR(50), 
ride_date DATE 
); 
INSERT INTO rides (ride_id, customer_name, company, ride_date) 
VALUES 
(1, 'Raj', 'Ola', '2024-12-01'), 
(2, 'Simran', 'Uber', '2024-12-03'), 
(3, 'Arjun', 'Ola', '2024-12-05'), 
(4, 'Deepa', 'Ola', '2024-12-10'), 
(5, 'Maya', 'Uber', '2024-12-15'); 

-- Q13 Count the number of Ola rides taken in December 2024. 
select * FROM rides 
where company = 'Ola'
and ride_date between '2024-12-01' and '2024-12-31';

select count(*) as ola_rides
FROM rides 
where company = 'Ola'
and ride_date between '2024-12-01' and '2024-12-31';
---------------------------------------------------------------------------
CREATE TABLE offices ( 
office_id INT PRIMARY KEY, 
company VARCHAR(50), 
city VARCHAR(50) 
); 
INSERT INTO offices (office_id, company, city) 
VALUES 
(1, 'TCS', 'Mumbai'), 
(2, 'Infosys', 'Bangalore'), 
(3, 'Wipro', 'Hyderabad'), 
(4, 'Wipro', 'Kolkata'), 
(5, 'Infosys', 'Chennai'); 

-- Q 14   List all cities where Wipro has offices. 
SELECT * from offices
where company = 'Wipro';

SELECT DISTINCT city 
FROM offices 
WHERE company = 'Wipro'; 

---------------------------------------------------------------------------
CREATE TABLE orders ( 
order_id INT PRIMARY KEY, 
company VARCHAR(50), 
amount DECIMAL(10, 2) 
); 
INSERT INTO orders (order_id, company, amount) 
VALUES 
(1, 'Zomato', 500.00), 
(2, 'Swiggy', 300.00), 
(3, 'Zomato', 700.00), 
(4, 'Swiggy', 200.00), 
(5, 'Zomato', 1000.00); 

-- Q 15 Find the total revenue generated by Zomato orders. 

SELECT sum(amount) as revenue
from orders
where company = 'Zomato';



